# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, null=True)),
                ('date', models.IntegerField(null=True)),
                ('month', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('pic', models.FileField(null=True, upload_to='pic')),
                ('time', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
