# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='feedback',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
