# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180716_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='cemail',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='email',
            new_name='femail',
        ),
    ]
