# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_contact_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.IntegerField(null=True)),
                ('zipcode', models.IntegerField(null=True)),
                ('demail', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(max_length=100)),
                ('ngo', models.CharField(choices=[('SP', 'Saras prayas'), ('V', 'Vikas'), ('PA', 'PAWS'), ('PF', 'Posh Foundation'), ('LN', 'Lakshyam NGO Delhi'), ('CW', 'Child & Women Care Society'), ('SA', 'Shivashrya'), ('SK', 'Satkartar')], max_length=2, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='ngo',
            field=models.CharField(choices=[('SP', 'Saras prayas'), ('V', 'Vikas'), ('PA', 'PAWS'), ('PF', 'Posh Foundation'), ('LN', 'Lakshyam NGO Delhi'), ('CW', 'Child & Women Care Society'), ('SA', 'Shivashrya'), ('SK', 'Satkartar')], max_length=2, null=True),
        ),
    ]
